/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'
import { Route as AppQuestionToeicIndexImport } from './routes/_app/question-toeic/index'
import { Route as AppGrammarsIndexImport } from './routes/_app/grammars/index'
import { Route as AppExamsIndexImport } from './routes/_app/exams/index'
import { Route as AppExamTipsIndexImport } from './routes/_app/exam-tips/index'
import { Route as AuthAuthRegisterImport } from './routes/_auth/auth/register'
import { Route as AuthAuthLoginImport } from './routes/_auth/auth/login'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppQuestionToeicIndexRoute = AppQuestionToeicIndexImport.update({
  path: '/question-toeic/',
  getParentRoute: () => AppRoute,
} as any)

const AppGrammarsIndexRoute = AppGrammarsIndexImport.update({
  path: '/grammars/',
  getParentRoute: () => AppRoute,
} as any)

const AppExamsIndexRoute = AppExamsIndexImport.update({
  path: '/exams/',
  getParentRoute: () => AppRoute,
} as any)

const AppExamTipsIndexRoute = AppExamTipsIndexImport.update({
  path: '/exam-tips/',
  getParentRoute: () => AppRoute,
} as any)

const AuthAuthRegisterRoute = AuthAuthRegisterImport.update({
  path: '/auth/register',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAuthLoginRoute = AuthAuthLoginImport.update({
  path: '/auth/login',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_auth/auth/login': {
      preLoaderRoute: typeof AuthAuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/_auth/auth/register': {
      preLoaderRoute: typeof AuthAuthRegisterImport
      parentRoute: typeof AuthImport
    }
    '/_app/exam-tips/': {
      preLoaderRoute: typeof AppExamTipsIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/exams/': {
      preLoaderRoute: typeof AppExamsIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/grammars/': {
      preLoaderRoute: typeof AppGrammarsIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/question-toeic/': {
      preLoaderRoute: typeof AppQuestionToeicIndexImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AppRoute.addChildren([
    AppExamTipsIndexRoute,
    AppExamsIndexRoute,
    AppGrammarsIndexRoute,
    AppQuestionToeicIndexRoute,
  ]),
  AuthRoute.addChildren([AuthAuthLoginRoute, AuthAuthRegisterRoute]),
])

/* prettier-ignore-end */
